name: Hello World

# Trigger the workflow on push events to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo text
        run: echo "Hello, world!"
